---
- hosts: vagrant
  become: true

  tasks:

    - name: Install required packages and update cache
      apt: name=apt-transport-https,ca-certificates,curl,software-properties-common update_cache=yes

    - name: Ensure repository key is installed
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present

    - name: Add docker repository and update cache
      apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable' state=present update_cache=yes

    - name: Install docker
      apt: name=docker-ce

    - name: Ensure docker-compose is installed and available
      get_url: 
        url : https://github.com/docker/compose/releases/download/1.19.0/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
        dest: /usr/local/bin/docker-compose
        mode: '+x'